language: node_js
node_js:
  - "10"

cache: yarn

install: yarn

jobs:
  include:
    - stage: npm release
      if: tag IS present
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
